name: Generate OpenStreetMap Garmin maps
on:
  push:
    branches:
      - matrix
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      downloads: ${{ steps.set-downloads.outputs.downloads }}
    steps:
      - uses: actions/checkout@v3
      - id: set-downloads
        run: echo "downloads=$(< downloads.json)" >> $GITHUB_OUTPUT
    
  download:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.downloads) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cached-download
        with:
          filename: ${{ matrix.filename }}
          url: ${{ matrix.url }}
