name: Update GitHub Action
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  update-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install mkgmap-github-action
        run: pipx install mkgmap-github-action

      - name: Run mkgmap-github-action
        run: mkgmap-github-action

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update GitHub Action'
          author_name: 'Github Action'
          author_email: github-action@mrns.nl
          committer_name: 'Github Action'
          committer_email: github-action@mrns.nl
